CREATE DATABASE IF NOT EXISTS uptime;
USE uptime;
CREATE TABLE response (Status INT, Site VARCHAR(20), Message VARCHAR(20), TimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP, JsTimeStamp VARCHAR(20), id INT NOT NULL AUTO_INCREMENT, primary key (id));
